"""Conservative rootfs cleanup performed after all chroot mounts are gone."""
from pathlib import Path
import shutil
from typing import Any

class ChrootCleaner:
    def __init__(self, target_root: Path, config: dict[str, Any]):
        self.root = Path(target_root).resolve()
        self.config = config.get("cleanup", {}) if isinstance(config, dict) else {}

    def _children(self, relative: str):
        directory = self.root / relative.lstrip("/")
        if not directory.is_dir() or directory.is_symlink():
            return []
        return list(directory.iterdir())

    @staticmethod
    def _remove(path: Path) -> bool:
        if path.is_symlink() or path.is_file():
            path.unlink(missing_ok=True)
        elif path.is_dir():
            shutil.rmtree(path)
        else:
            return False
        return True

    def _empty(self, relative: str, preserve: set[str] = set()) -> int:
        count = 0
        for child in self._children(relative):
            if child.name in preserve:
                continue
            try:
                count += int(self._remove(child))
            except OSError:
                continue
        return count

    def clean(self) -> dict[str, int]:
        if self.config.get("enabled", True) is False or not self.root.is_dir():
            return {}
        report = {"removed": 0}
        if self.config.get("apt_lists", True):
            report["removed"] += self._empty("var/lib/apt/lists", {"partial"})
        if self.config.get("apt_archives", True):
            report["removed"] += self._empty("var/cache/apt/archives", {"partial"})
        if self.config.get("logs", True):
            report["removed"] += self._empty("var/log")
            report["removed"] += self._empty("var/log/journal")
        if self.config.get("temporary", True):
            report["removed"] += self._empty("tmp")
            report["removed"] += self._empty("var/tmp")
        if self.config.get("caches", True):
            report["removed"] += self._empty("root/.cache")
            for home in self._children("home"):
                if home.is_dir() and not home.is_symlink():
                    report["removed"] += self._empty(str(home.relative_to(self.root) / ".cache"))
        if self.config.get("bytecode", True):
            for directory in self.root.rglob("__pycache__"):
                if directory.is_dir() and not directory.is_symlink():
                    try:
                        shutil.rmtree(directory); report["removed"] += 1
                    except OSError:
                        pass
            for bytecode in self.root.rglob("*.py[co]"):
                if bytecode.is_file() and not bytecode.is_symlink():
                    try: bytecode.unlink(); report["removed"] += 1
                    except OSError: pass
        if self.config.get("builder_metadata", True):
            for relative in (".deb-dev-builder-bootstrap.json", "run/deb-dev-builder-hooks"):
                candidate = self.root / relative
                if candidate.exists() or candidate.is_symlink():
                    try: report["removed"] += int(self._remove(candidate))
                    except OSError: pass
        if self.config.get("machine_identity", True):
            for relative in ("etc/machine-id", "var/lib/dbus/machine-id", "root/.bash_history"):
                candidate = self.root / relative
                if candidate.exists() or candidate.is_symlink():
                    try: report["removed"] += int(self._remove(candidate))
                    except OSError: pass
        # APT optimisation is generated by this builder and never belongs in the image.
        apt_opt = self.root / "etc/apt/apt.conf.d/99optimize"
        if apt_opt.exists():
            try: apt_opt.unlink(); report["removed"] += 1
            except OSError: pass
        return report
