---
crypttabOptions: luks
mountOptions:
    - filesystem: default
      options: [ defaults, noatime ]
    - filesystem: efi
      options: [ defaults, noatime, umask=0077 ]
    - filesystem: ext4
      options: [ defaults, noatime ]
    - filesystem: btrfs
      options: [ defaults, noatime, compress=zstd:3, discard=async ]
