# Debian/Devuan GRUB configuration.
---
overwrite: true
prefer_grub_d: true
keepDistributor: false
kernel_params: [ "quiet", "splash" ]
defaults:
    GRUB_DISTRIBUTOR: "Deb-Dev Modern"
    GRUB_TIMEOUT: 5
    GRUB_DEFAULT: 0
    GRUB_DISABLE_SUBMENU: true
    GRUB_GFXMODE: "auto"
    GRUB_GFXPAYLOAD_LINUX: "keep"
    GRUB_DISABLE_RECOVERY: false
    GRUB_DISABLE_OS_PROBER: false
always_use_defaults: true
