---
efiSystemPartition: "/boot/efi"
efiSystemPartitionSize: 800M
efiSystemPartitionName: EFI
userSwapChoices: [ none, small, suspend, reuse, file ]
swapPartitionName: SWAP
drawNestedPartitions: false
alwaysShowPartitionLabels: true
allowManualPartitioning: true
initialPartitioningChoice: none
initialSwapChoice: none
defaultFileSystemType: "ext4"
availableFileSystemTypes: [ ext4, btrfs, f2fs, xfs ]
