---
defaultGroups:
    - lp
    - cdrom
    - floppy
    - sudo
    - video
    - audio
    - dip
    - plugdev
    - netdev
    - lpadmin
    - scanner
    - bluetooth
    - sambashare
    - users
autologinGroup: autologin
writeUserPasswordToConsole: false
sudoersGroup: sudo
setRootPassword: true
