# Calamares settings for Devuan non-systemd installations.
---
modules-search: [ local, /usr/lib/calamares/modules ]
sequence:
  - show: [ welcome, locale, keyboard, partition, users, summary ]
  - exec:
    - partition
    - mount
    - unpackfs
    - machineid
    - fstab
    - locale
    - keyboard
    - localecfg
    - removeuser
    - users
    - displaymanager
    - networkcfg
    - packages
    - hwclock
    - grubcfg
    - bootloader
    - umount
  - show: [ finished ]
branding: deb-dev-modern
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
